#ifndef LIBPHPEXT_H
#define LIBPHPEXT_H

#define LIBPHPEXT_VERSION "4.0.0"

#include "src/vendor.h"
#include "src/argument_entry.h"
#include "src/array.h"
#include "src/array_iterator.h"
#include "src/attribute_entry.h"
#include "src/callable.h"
#include "src/callback.h"
#include "src/class_basic.h"
#include "src/class_entry.h"
#include "src/constant_entry.h"
#include "src/conversion.h"
#include "src/dependency_entry.h"
#include "src/encoding.h"
#include "src/environ.h"
#include "src/exception.h"
#include "src/function_entry.h"
#include "src/function_entry_method.h"
#include "src/hash.h"
#include "src/hook_entry.h"
#include "src/ini_entry.h"
#include "src/module_entry.h"
#include "src/object.h"
#include "src/parameter.h"
#include "src/property_entry.h"
#include "src/property_refer.h"
#include "src/property_value.h"
#include "src/runtime.h"
#include "src/string_buffer.h"
#include "src/string_builder.h"
#include "src/string.h"
#include "src/type_code.h"
#include "src/util.h"
#include "src/value.h"
#include "src/value_basic.h"
#include "src/vendor.h"

#endif // LIBPHPEXT_H
